### PR TITLE
Update for Python 3

### PR DESCRIPTION
**Pull request by iCarossio**
Hi,
My friend @bathal1 and I tried to make a working version of w3af REST API client for Python 3. We have been using it on Kali Linux 2018.2 with the last version of w3af and Python 3.6/7, and we have not encountered any issue so far.

We hope it will be useful :)

### CODE REVIEW

**Comment by andresriancho** [comment]
@iCarossio @bathal1 , thanks for your work on this! :+1: 

I don't have any experience with py3k, so please bare with my newbie questions :-)

 * After applying this PR, the code will **only** work on py3k, correct? If so, is there a way to make the code compatible with both python versions?
 * Have you used any tool (does it exist?) to identify any areas of the code which are not py3k valid?

**Comment by iCarossio** [comment]
Hi @andresriancho , you're welcome :)
- Actually we didn't try to use this PR with Python 2, and we're are not sure about the backward compatibility. Maybe this issue deserves more tests...
- Yes, we mainly used [2to3](https://docs.python.org/3.7/library/2to3.html) to help us with this porting.

**Comment by andresriancho** [comment]
I don't want your work to go to waste. And at the same time I don't want to merge it as-is because that will break python2 support.

As far as I can see these are the options we have:
 * I create a new repository called `w3af-api-client-3` and merge your work. That repository would be the client that all python3k projects would use to communicate with the w3af api.
 * You change the code in such a way that it works for both python2 and 3, and I merge that into this repository

The second option is preferred, but I would gladly go with the first one too.

**Comment by andresriancho** [comment]
py3k support implemented via another PR

**Pull request closed without merging**
